### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by fterrag** [MEDIGO/go-zendesk#86]
Hey there,

Thank you for creating and maintaining this package - it's been very useful! I was wondering if there was a way to fetch groups? I see that there is a Group struct defined, but I'm not seeing how to fetch groups from Zendesk.

Thanks!

**Comment by eggman64** [comment]
https://github.com/MEDIGO/go-zendesk/pull/63/files We received a PR with the group methods. Unfortunately it was missing test cases. Since `Groups` are not a business priority for us, this has got overlooked. Perhaps you would like to take over the code from the PR, add a few test cases and send us a new PR?

**Comment by fterrag** [comment]
@eggman64 thanks for the quick reply. Take a look at #87. Thanks!
